projects:
  RestaurantLocationAPI:
    schemaPath: src/graphql/schema.json
    includes:
      - src/models/schema.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/models
